import Sidebar from './_components/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-indigo-50 w-full flex justify-center `}>
        <div className='relative w-[1520px] max-w-[1520px] flex gap-4'>
          <div className='w-[420px]'>
            <Sidebar/>
          </div>
          <div className='w-full flex justify-center items-start'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
